name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup node.js
      uses: actions/setup-node@v1.1.0
      with:
        version: 12.x
    - run: npm install
      working-directory: frontend
    - run: npm run build:prod
      working-directory: frontend
    - uses: actions/upload-artifact@v1
      with:
        name: frontend-ssr
        path: frontend/dist-ssr
    - uses: actions/upload-artifact@v1
      with:
        name: frontend-client
        path: frontend/dist-client
    - uses: actions/upload-artifact@v1
      with:
        name: backend
        path: backend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: frontend-ssr
        path: artifact/frontend-ssr
    - uses: actions/download-artifact@v1
      with:
        name: frontend-client
        path: artifact/frontend-client
    - uses: actions/download-artifact@v1
      with:
        name: backend
        path: artifact/backend
    - name: Upload artifacts to target server
      run: |
        compgen -c
        echo $TMPDIR
        echo ${{ secrets.DEPLOY_KEY }} > $TMPDIR/tmp_id_rsa
        rsync -e "ssh -i $TMPDIR/tmp_id.rsa" artifact/frontend-ssr ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:/data/sites/web/drentsheideschaapnl/ssr
        rm $TMPDIR/tmp_id_rsa