name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup node.js
      uses: actions/setup-node@v1.1.0
      with:
        version: 12.x
    - run: npm install
      working-directory: frontend
    - run: npm run build:prod
      working-directory: frontend
    - uses: actions/upload-artifact@v1
      with:
        name: frontend-ssr
        path: frontend/dist-ssr
    - uses: actions/upload-artifact@v1
      with:
        name: frontend-client
        path: frontend/dist-client
    - uses: actions/upload-artifact@v1
      with:
        name: backend
        path: backend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: frontend-ssr
        path: artifact/frontend-ssr
    - uses: actions/download-artifact@v1
      with:
        name: frontend-client
        path: artifact/frontend-client
    - uses: actions/download-artifact@v1
      with:
        name: backend
        path: artifact/backend
    - name: Upload artifacts to target server
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$DEPLOY_KEY" > /tmp/tmp_id_rsa
        chmod 600 /tmp/tmp_id_rsa
        rsync --delete -r -e "ssh -o StrictHostKeyChecking=no -i /tmp/tmp_id_rsa" \
          --exclude '.htaccess' \
          artifact/frontend-ssr $DEPLOY_USERNAME@$DEPLOY_HOST:/data/sites/web/drentsheideschaapnl/ssr \
          artifact/frontend-client $DEPLOY_USERNAME@$DEPLOY_HOST:/data/sites/web/drentsheideschaapnl/subsites/nieuw.drentsheideschaap.nl \
          artifact/backend $DEPLOY_USERNAME@$DEPLOY_HOST:/data/sites/web/drentsheideschaapnl/subsites/nieuw.drentsheideschaap.nl
        rm /tmp/tmp_id_rsa