name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup node.js
      uses: actions/setup-node@v1.1.0
      with:
        version: 12.x
    - run: npm install
      working-directory: frontend
    - run: npm run build:prod
      working-directory: frontend
    - uses: actions/upload-artifact@v1
      with:
        name: frontend-ssr
        path: frontend/dist-ssr
    - uses: actions/upload-artifact@v1
      with:
        name: frontend-client
        path: frontend/dist-client
    - uses: actions/upload-artifact@v1
      with:
        name: backend
        path: backend

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        port: ${{ secrets.DEPLOY_PORT }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
        script: |
          echo Hello world